platform :android do

  desc "Build signed AAB and APK"
  lane :build_internal do

    gradle(task: "clean")
    gradle(task: "bundleRelease")
    gradle(task: "assembleRelease")

    puts "✅ Build successful. Signed AAB and APK generated."
  end

end