platform :android do
  desc "Build Debug APK"
  lane :build_internal do
    gradle(
      task: "clean"
    )

    gradle(
      task: "assembleDebug"
    )

    puts "✅ Debug APK generated."
  end
end