name: Test Android CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Fastlane
        run: gem install fastlane

      - name: Grant Gradle Permission
        run: chmod +x gradlew

      - name: Run Fastlane Build (Creates AAB)
        run: fastlane android build_internal

      # ✅ Download bundletool
      - name: Download bundletool
        run: |
          curl -L -o bundletool.jar \
          https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar

      # ✅ Convert AAB → Universal APK
      - name: Convert AAB to Universal APK
        run: |
          java -jar bundletool.jar build-apks \
            --bundle=app/build/outputs/bundle/release/app-release.aab \
            --output=app.apks \
            --mode=universal

          unzip app.apks -d apks

      # ✅ Upload AAB
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/app-release.aab

      # ✅ Upload Universal APK
      - name: Upload Universal APK
        uses: actions/upload-artifact@v4
        with:
          name: universal-apk
          path: apks/universal.apk